covid19db/fetchers-python

- src/main.py
- src/plugins/ES-MSW/fetcher.py
- src/plugins/ES-MSW/utils.py
Adapted directly from the Piotr's code. I have just changed how to parse the data. A few lines when the upsert_obj is created.
> Add Spanish fetcher

- README.md
- src/fetcher_BRA_MSHM.py
- src/fetcher_SWE_GM.py
- src/fetcher_ZAF.py
Python fetcher for South Africa data:
to make use of utils.fetcher_abstract, I stored it in this directory
> Create fetcher for South Africa data

- README.md
- src/plugins/AUS_C1A/fetcher.py
- src/plugins/KOR_DS4C/fetcher.py
Added fetchers for South Korea and Australia.
> KOR_DS4C and AUS_C1A

- README.md
- src/plugins/IND_COVIND/fetcher.py
- src/plugins/IND_COVIND/translation.csv
- src/plugins/IND_COVIND/utils.py
- src/plugins/THA_STAT/fetcher.py
- src/plugins/THA_STAT/translation.csv
Added fetchers for India and Thailand.
> IND_COVIND and THA_STAT

- src/plugins/CZE_ZH/fetcher.py
- src/plugins/CZE_ZH/translation.csv
Currently crashing on reading 'Nezjištěno', which is not in dictionary
> Creating CzechiaFetcher

- src/adapters/postgresql.py
- src/main.py
- src/utils/email.csv
- src/utils/email.py
- src/utils/validation.py
changes to "main.py"
Changes to "postgresql,p"
added email.py , validation.py, email.csv to ./src/utils
two new  DB tables available in play : "staging_epidemiology" and "url_info"
two new functions in play : covid19_schema.send_validated_data, covid19_schema.covid19_compare_tables
> validation model

- src/plugins/APPLE_MOBILITY/utils.py
Enforce utf-8 encoding for request.text.
> Fix encoding

- src/plugins/AUS_C1A/fetcher.py
- src/plugins/KOR_DS4C/fetcher.py
- src/plugins/LAT_DSRP/fetcher.py
- src/plugins/THA_STAT/fetcher.py
Refactored fetchers for Australia, South Korea, Latin America and Thailand.
> Refactor AUS_C1A, KOR_DS4C, LAT_DSRP and THA_STAT

- src/plugins/PAK_GOV/utils.py
Legend entries not always int, date coding changed for Unix
> PAK_GOV bug fix

- src/plugins/PRT_MSDS/translation.csv
All previous data for Portugal should be deleted from the database before running this fetcher
> Repaired Portuguese translation.csv

- src/plugins/IND_COVIND/fetcher.py
> IND_COVIND

- src/plugins/RUS_GOV/translation.csv
Previously fetched records should be edited as well
> Correct error in RUS_GOV translation.csv

- src/utils/diagnostics.py
Quick fix to skip diagnostics if writing to CSV, as this causes exception
> Skip diagnostics for CSV adapter

- src/plugins/FRA_SPF/fetcher.py
- src/plugins/ITA_PC/fetcher.py
Fixed fetchers for France and Italy.
> FRA_SPF and ITA_PC

- src/plugins/MYS_MHYS/fetcher.py
1. Corrected handling of '-' as missing value
2. Fixed hospitalised (should be hospitalised_icu instead)
3. Fixed incorrect nesting of for loops
> Fix MYS_MHYS

- src/plugins/WEATHER/fetcher.py
- src/plugins/WEATHER/utils.py
> Fix WEATHER

- README.md
- src/plugins/BEL_SCI/fetcher.py
- src/plugins/BEL_SCI/translation.csv
> Implementing Belgium Fetcher BEL_SCI

- src/plugins/WRD_ECDC/fetcher.py
Rename other to other continent, fix future warnings
> Continental

- README.md
- src/plugins/LBN_GOV/fetcher.py
- src/plugins/LBN_GOV/translation.csv
- src/plugins/UAE_GOV/fetcher.py
Lebanon national and regional data
UAE national data
> Lebanon UAE fetchers

- src/plugins/AUS_C1A/fetcher.py
> Fix AUS_C1A

- README.md
- src/plugins/IRQ_GOV/fetcher.py
- src/plugins/IRQ_GOV/translation.csv
- src/plugins/LBN_GOV/fetcher.py
- src/plugins/SAU_GOV/fetcher.py
- src/plugins/SAU_GOV/translation.csv
Lebanon - Saudi Arabia -Iraq Fetchers
> Lebanon - Saudi Arabia -Iraq Fetchers

- src/plugins/GBR_NIDH/bridging_data.csv
- src/plugins/GBR_NIDH/fetcher.py
- src/plugins/GBR_NIDH/translation.csv
Fix GIDs for Level 3
Fix small errors in translation.csv
Add more bridging data so fetcher can be reset
> GBR_NIDH - Level3

- src/plugins/KOR_DS4C/fetcher.py
Disabled the Korean fetcher due to dataset deletion: https://github.com/jihoo-kim/Data-Science-for-COVID-19/commit/97adc4db850af2ad5a8c13a76a49cb2171946900
> Temporarily disable KOR_DS4C

- src/plugins/GBR_PHTW/fetcher.py
- src/plugins/GBR_PHTW/translation.csv
Accidentally turned off fetcher - now only turned off for Northern Irish LAUs
Fixed City & Hackney issue in translation.csv
> Fix GBR_PHTW

- src/plugins/GBR_NIDH/bridging_data.csv
- src/plugins/GBR_NIDH/fetcher.py
Also improve error collection for selenium
> Fix dates in GBR_NIDH

- src/plugins/APPLE_MOBILITY/fetcher.py
- src/plugins/WRD_WHOJHU/fetcher.py
- src/plugins/WRD_WHOJHU/utils.py
- src/utils/country_codes_translator/wikipedia-iso-country-codes.csv
Changes to CountryCodeTranslator and to WRD_WHOJHU translation method
> Standardize Country Names

- src/plugins/PAK_GOV/fetcher.py
- src/plugins/PAK_GOV/utils.py
Collect raw data for inspection
> PAK_GOV Debuggin

- src/plugins/PAK_GOV/fetcher.py
- src/plugins/PAK_GOV/utils.py
New parsing ability for new date and value formats.
> Fix PAK_GOV

- src/plugins/GBR_PHE/fetcher.py
- src/plugins/GBR_PHE/translation.csv
- src/plugins/GBR_PHW/fetcher.py
- src/plugins/GBR_PHW/translation.csv
Full coverage of UK through four national fetchers in preparation for turning off GBR_PHTW
> Expand GBR_PHE, GBR_PHW

- src/plugins/NGA_CDC/fetcher.py
- src/plugins/NGA_CDC/translation.csv
Collect national data from Nigerian CDC as NGA_SO seems broken
> NGA_CDC national data

- src/plugins/GBR_PHE/fetcher.py
- src/plugins/GBR_PHE/translation.csv
> Fix GBR_PHE

- src/plugins/IND_COVIND/fetcher.py
Fixed fetcher for India. Fun fact: in the past, the API used no years for case_time_series.csv, assuming that the year will always be 2020. They finally fixed it now.
> Fix IND_COVIND

- src/plugins/ESP_MS/fetcher.py
Fixed fetcher for Spain. From 22.10.2020 onwards, hospitalised_icu became non-cumulative so we skipped it to avoid double counting.
> Fix ESP_MS

- src/plugins/IRQ_GOV/fetcher.py
Source made structural element changes.
> Iraq fetcher Update

- src/plugins/CAN_GOV/fetcher.py
- src/plugins/GOOGLE_MOBILITY/fetcher.py
Update CAN_GOV for new source format. Cannot test as my machine is not loading the URL correctly, but should work fine!
> CAN_update

- src/plugins/GOOGLE_MOBILITY/fetcher.py
- src/plugins/NGA_SO/fetcher.py
Remove commas from one data field
> Nga so update

- src/plugins/DEU_JPGG/fetcher.py
Fixed fetcher for Germany (after Gehrcke disabled the HTTP API in Feb 2021).
> Fix DEU_JPGG

- src/plugins/FRA_SPF/fetcher.py
> Fix FRA_SPF

- README.md
- src/plugins/ESP_ISCIII/fetcher.py
- src/plugins/ESP_ISCIII/translation.csv
Added fetcher for Spain. As stated on their documentación y datos page, ISCIII data are optimised for real-time decision making and not statistical modeling. Use with caution.
> ESP_ISCIII

- src/plugins/THA_STAT/fetcher.py
Fixed fetcher for Thailand. The case summary in API v2 contains no timeline history, so there will be potential gaps in regional data whenever the API is down.
> Fix THA_STAT

- src/plugins/WEATHER/fetcher.py
The adapter expects the gid to be of type list.
> Fix MET fetcher

- src/plugins/GBR_PHW/fetcher.py
- Change URL address for GBR_PHW
- Should be possible to collect automatically from the dashboard; consider if this recurs as this is not the first time
- Download Excel sheet only once
> GBR_PHW - change URL

- src/adapters/csvfile.py
- src/adapters/postgresql.py
- src/plugins/WRD_ECDC/fetcher.py
- src/utils/diagnostics.py
Amend fetcher for new file format
> WRD_ECDC_WEEKLY

- src/plugins/GBR_NIDH/fetcher.py
- src/plugins/GBR_PHE_MSOA/fetcher.py
- src/plugins/IRL_HSPC/fetcher.py
- src/plugins/SWE_GM/fetcher.py
- src/plugins/TUR_MHOE/fetcher.py
- src/plugins/WRD_WHOJHU/fetcher.py
Edit filename in GBR_NIDH
Change source dataset for IRL_HSPC for historic coverage
Handle Winter Olympics in WHO_JHU
Turn off TUR_MHOE, SWE_GM, GBR_PHE_MSOA as they do not work and are not needed
> Minor changes, turning off old fetchers
